### ISSUE TITLE
The script is reporting "cp: cannot stat" error when trying to run the script

### ISSUE THREAD

**Issue by rsramkis** [DimaZirix/fedora-gdm-wallpaper#2]
I was trying to set the startup wallpaper I am getting the following error:

`sudo bash set-gdm-wallpaper.sh ./wallhaven-r2d9oq.jpg
Updating wallpaper...
cp: cannot stat './wallhaven-r2d9oq.jpg': No such file or directory`

The directory where the files are as follows:

`[rsruser@hanna GDM Wallpaper]$ ls -al
total 8500
drwxr-xr-x  2 rsruser rsruser    4096 Oct 13 21:29 .
drwxr-xr-x 12 rsruser rsruser    4096 Sep 28 20:24 ..
-rw-r--r--  1 rsruser rsruser  511328 Oct 13 21:27 fedora-gdm-wallpaper-master.zip
-rw-r--r--  1 rsruser rsruser  508326 Oct 13 15:17 gdm-wallpaper.tar.gz
-rwxr-xr-x  1 rsruser rsruser    4023 Sep  2 08:57 set-gdm-wallpaper.sh
-rw-r--r--  1 rsruser rsruser 7664799 Aug 21 19:17 wallhaven-r2d9oq.jpg
[rsruser@hanna GDM Wallpaper]$ 
`

**Comment by DimaZirix** [comment]
Thanks for report.

Fixed. 
Please check it.

**Comment by rsramkis** [comment]
> Thanks for report.
> 
> Fixed.
> Please check it.

Hi DimaZirix,

I re-tested and the login screen on Manjaro (Gnome 3.34.1) now gets updated with the image I set (thank you). There is a new issue I in regards to the login screen wallpaper not setting the correct size. I will file a separate defect for this. Thanks again for creating this script.
