### ISSUE TITLE
When using an image which has a higher resolution then the login screen the image is not resized automatically

### ISSUE THREAD

**Issue by rsramkis** [DimaZirix/fedora-gdm-wallpaper#3]
When using the latest version of this fedora-gdm-wallpaper script I noticed that it does not automatically set the login screen image to match the desktop resolution. In my case:

**Desktop Resolution:** 1600 x 900
**Test Image Resolution:** 3840 x 2160

When I used the original image (see attached test file "wallhaven-r2d9oq.jpg") the login screen image does not show correctly (you see a portion of the image).

**Workaround**
But when I use the manually resized (see "wallhaven-r2d9oq-resized.jpg") the image will centers on the screen correctly.

With the older script I did not have to resize the image this way.

![wallhaven-r2d9oq](https://user-images.githubusercontent.com/14362317/66938936-13922a80-f010-11e9-865d-f5bbf98a8cec.jpg)
![wallhaven-r2d9oq-resize](https://user-images.githubusercontent.com/14362317/66938968-2573cd80-f010-11e9-813b-61f59bd584b7.jpg)

**Comment by DimaZirix** [comment]
This is result of issue https://github.com/DimaZirix/fedora-gdm-wallpaper/issues/1
CSS option, for resizing image, work incorrectly with dual monitors.

I will add flag to activate resizing
