### ISSUE TITLE
Facing issue on Fedora 38

### ISSUE THREAD

**Issue by IwataNeo** [DimaZirix/fedora-gdm-wallpaper#5]
I am facing an issue in Fedora 38. My Wallpaper will be displayed at first, but then it disappears and the standart grey colored background will be displayed. Any idea on how to resolve this issue?

**Comment by rsramkis** [comment]
On a side note, I also tested the original release and was able to reproduce the issue with Gnome 44.1 on Arch Linux (via EndeavourOS). As soon as the fix is released I can also help you test. 

Thank you all for your hard work and attention.
